Add a missing include
Addressing:
/home/jcerny/openscap/src/OVAL/probes/crapi/digest.c: In function ‘crapi_mdigest_fd’:
/home/jcerny/openscap/src/OVAL/probes/crapi/digest.c:76:38: warning: implicit declaration of function ‘malloc’ [-Wimplicit-function-declaration]
         struct digest_ctbl_t *ctbl = malloc(num * sizeof(struct digest_ctbl_t));
                                      ^~~~~~
/home/jcerny/openscap/src/OVAL/probes/crapi/digest.c:76:38: warning: incompatible implicit declaration of built-in function ‘malloc’
/home/jcerny/openscap/src/OVAL/probes/crapi/digest.c:76:38: note: include ‘<stdlib.h>’ or provide a declaration of ‘malloc’
/home/jcerny/openscap/src/OVAL/probes/crapi/digest.c:187:9: warning: implicit declaration of function ‘free’ [-Wimplicit-function-declaration]
         free(ctbl);
         ^~~~
/home/jcerny/openscap/src/OVAL/probes/crapi/digest.c:187:9: warning: incompatible implicit declaration of built-in function ‘free’
/home/jcerny/openscap/src/OVAL/probes/crapi/digest.c:187:9: note: include ‘<stdlib.h>’ or provide a declaration of ‘free’