Include collectVarRefs_impl.h because of oval_obj_collect_var_refs
Addressing:
oval_probe.c: In function 'oval_probe_query_object':
oval_probe.c:279:3: warning: implicit declaration of function 'oval_obj_collect_var_refs'