Add missing include
Addressing:

/home/jcerny/openscap/tests/probes/sysinfo/test_probes_sysinfo.c: In
function ‘main’:
/home/jcerny/openscap/tests/probes/sysinfo/test_probes_sysinfo.c:34:10:
warning: implicit declaration of function ‘oval_probe_query_sysinfo’;
did you mean ‘oval_probe_session_new’? [-Wimplicit-function-declaration]
assert(oval_probe_query_sysinfo(sess, &info) == 0);