Prevent double free
SEAP_cmd_exec can return the args argument as the return value and
and as a result it can be freed in __SEAP_cmdexec_reply.

Error: USE_AFTER_FREE (CWE-416): [#def451] [important]
openscap-1.3.4/src/OVAL/probes/SEAP/seap.c:302: freed_arg: "__SEAP_cmdexec_reply" frees "cmd->args".
openscap-1.3.4/src/OVAL/probes/SEAP/seap.c:305: double_free: Calling "SEXP_free" frees pointer "cmd->args" which has already been freed.
  303|
  304|                           if (cmd->args != NULL)
  305|->                                 SEXP_free(cmd->args);
  306|
  307|                           return (ret);