Covscan fixes (SHELLCHECK), small refactoring in Shell wrappers
Error: SHELLCHECK_WARNING:
warning: die references arguments, but none are ever passed. [SC2120]

Error: SHELLCHECK_WARNING:
warning: Use 'cd ... || exit' or 'cd ... || return' in case cd fails. [SC2164]

Error: SHELLCHECK_WARNING:
warning: Declare and assign separately to avoid masking return values. [SC2155]