Fix debug.c for cross compilation
I can't find any header name flock.h. On Linux, flock() function is
located in sys/file.h, for other platforms we have a fallback function.
On the other hand, there's a missing include.
Adressing:
/home/jcerny/openscap/src/common/debug.c: In function 'get_program_name':
/home/jcerny/openscap/src/common/debug.c:91:25: warning: implicit declaration of function 'GetModuleFileName' [-Wimplicit-function-declaration]
         int path_size = GetModuleFileName(NULL, path, sizeof(path) - 1);
                         ^~~~~~~~~~~~~~~~~

to squah with 328ce668cf293bb7efc6e52824424c6bf792e3c