Export remaining symbols from public API
These symbols are supposed to be a part of pubilc API, but they
have been forgotten to be labeled by OSCAP_API macro. Due to
coincidens with Issue #963 this problem was not visible. After
Issue #936 has been fixed this issue poped by by breaking our
upstream tests of SWIG Python 3 Bindings.
Addressing this traceback and also many other similar tracebacks:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/jenkins/workspace/openscap-master-pull-requests/build/swig/python3/openscap_api.py", line 49, in <module>
    OSCAP = _import_helper()
  File "/home/jenkins/workspace/openscap-master-pull-requests/build/swig/python3/openscap_api.py", line 45, in _import_helper
    _mod = imp.load_module('_openscap_py', fp, pathname, description)
  File "/usr/lib64/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib64/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: /home/jenkins/workspace/openscap-master-pull-requests/build/swig/python3/_openscap_py.so: undefined symbol: OSCAP_LANG_DEFAULT