Fix broken master build with SCE
Some of the symbols from src/common/oscap_string.h header file are required
to build SCE library. In maint-1.2, those symbols are visible, however in
master branch the symbols are hidden. This causes that SCE doesn't build on
master branch using automake. Therefore it would be difficult to try
that using cmake.

Addressing:
make[2]: Entering directory '/home/jcerny/openscap/src/SCE'
  CC       sce_engine.lo
  CC       module_entry.lo
  CCLD     libopenscap_sce.la
.libs/sce_engine.o: In function `_pipe_try_read_into_string':
/home/jcerny/openscap/src/SCE/sce_engine.c:329: undefined reference to
`oscap_string_append_char'
.libs/sce_engine.o: In function `_pipe_try_read_into_string':
sce_engine.c:(.text+0xa7): undefined reference to
`oscap_string_append_string'
.libs/sce_engine.o: In function `sce_engine_eval_rule':
sce_engine.c:(.text+0xa8f): undefined reference to `oscap_string_new'
sce_engine.c:(.text+0xa97): undefined reference to `oscap_string_new'
sce_engine.c:(.text+0xdc6): undefined reference to
`oscap_string_bequeath'
sce_engine.c:(.text+0xdd1): undefined reference to
`oscap_string_bequeath'
/usr/bin/ld: .libs/libopenscap_sce.so.8.13.0: hidden symbol
`oscap_string_new' isn't defined
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:1306: libopenscap_sce.la] Error 1
make[2]: Leaving directory '/home/jcerny/openscap/src/SCE'
make[1]: *** [Makefile:1538: all-recursive] Error 1
make[1]: Leaving directory '/home/jcerny/openscap'
make: *** [Makefile:1347: all] Error 2