new glibc forces us to use _DEFAULT_SOURCE
but we keep _BSD_SOURCE here for compatibility with older libc.

Addressing:
In file included from /usr/include/string.h:25:0,
                 from cpename.c:37:
/usr/include/features.h:148:3: error: #warning "_BSD_SOURCE and
_SVID_SOURCE are deprecated, use _DEFAULT_SOURCE" [-Werror=cpp]
 # warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use
 # _DEFAULT_SOURCE"