Avoid use of O_CLOEXEC.
It breaks RHEL5 build and this fd gets closed immediatelly anyway.

Addressing:
elements.c: In function 'oscap_xml_save_filename':
elements.c:176: error: 'O_CLOEXEC' undeclared (first use in this function)
elements.c:176: error: (Each undeclared identifier is reported only once
elements.c:176: error: for each function it appears in.)