Do not specify fully versioned arch-specific requires for noarch packages
The Packaging:Guidelines#Requiring_Base_Package explicitly prohibits this
by:

    When a subpackage requires the base package, it must do so using
    a fully versioned arch-specific (for non-noarch packages) dependency.
                                         ^^^

Addressing:
BuildError: mismatch when analyzing openscap-content-sectool-0.9.13-5.fc21.noarch.rpm, rpmdiff output was:
removed     REQUIRES openscap(armv7hl-32) = 0.9.13-5.fc21
removed     REQUIRES openscap-engine-sce(armv7hl-32)
added       REQUIRES openscap(x86-64) = 0.9.13-5.fc21
added       REQUIRES openscap-engine-sce(x86-64)