Added a missing oscap_debug.h include to oscap-ds.c
Resolves:
../../utils/oscap-ds.c: In function ‘app_ds_rds_validate’:
../../utils/oscap-ds.c:521: warning: implicit declaration of function ‘oscap_set_verbose’