Include collectVarRefs_impl.h because of oval_ste_collect_var_refs
Addressing:
oval_resultTest.c: In function '_oval_result_test_initialize_bindings':
oval_resultTest.c:1508:3: warning: implicit declaration of function 'oval_ste_collect_var_refs'