Fix build due to unresolved unitdir
According to Fedora packaging guidelines
https://fedoraproject.org/wiki/Packaging:Systemd#Filesystem_locations
in order for the %{_unitdir} macro to exist, our package must have
BuildRequires: systemd.

Addressing:
error: File not found: /builddir/build/BUILDROOT/openscap-1.3.7-0.20220830091921540256.pr1882.62.g2bc28fe27.fc38.x86_64/usr/libexec/oscap-remediate
error: File must begin with "/": %{_unitdir}/oscap-remediate.service
error: File must begin with "/": %{_unitdir}/system-update.target.wants/
    File not found: /builddir/build/BUILDROOT/openscap-1.3.7-0.20220830091921540256.pr1882.62.g2bc28fe27.fc38.x86_64/usr/libexec/oscap-remediate
    File must begin with "/": %{_unitdir}/oscap-remediate.service
    File must begin with "/": %{_unitdir}/system-update.target.wants/