Add a missing free
Error: RESOURCE_LEAK (CWE-772): [#def178] [important]
openscap-1.3.4/src/DS/ds_common.c:68: alloc_fn: Storage is returned from allocation function "oscap_sprintf".
openscap-1.3.4/src/DS/ds_common.c:68: var_assign: Assigning: "filename" = storage returned from "oscap_sprintf("%s/%s", target_dir, oscap_source_readable_origin(s))".
openscap-1.3.4/src/DS/ds_common.c:70: noescape: Resource "filename" is not freed or pointed-to in "oscap_acquire_ensure_parent_dir".
openscap-1.3.4/src/DS/ds_common.c:73: leaked_storage: Variable "filename" going out of scope leaks the storage it points to.
   71|   		if (ret != 0) {
   72|   			oscap_htable_iterator_free(hit);
   73|-> 			return ret;
   74|   		}
   75|   		ret = oscap_source_save_as(s, filename);