Fix freshly introduced warnings.
Addressing:
oscap_acquire.c: In function 'oscap_acquire_url_download':
oscap_acquire.c:146:32: warning: implicit declaration of function
'oscap_buffer_new' [-Wimplicit-function-declaration]
  struct oscap_buffer* buffer = oscap_buffer_new();
                                ^
oscap_acquire.c:146:32: warning: initialization makes pointer from
integer without a cast [-Wint-conversion]
oscap_acquire.c:157:3: warning: implicit declaration of function
'oscap_buffer_free' [-Wimplicit-function-declaration]
   oscap_buffer_free(buffer);
   ^
oscap_acquire.c:161:17: warning: implicit declaration of function
'oscap_buffer_get_length' [-Wimplicit-function-declaration]
  *memory_size = oscap_buffer_get_length(buffer);
                 ^
oscap_acquire.c:162:15: warning: implicit declaration of function
'oscap_buffer_bequeath' [-Wimplicit-function-declaration]
  char* data = oscap_buffer_bequeath(buffer); // get data and free
buffer struct
               ^
oscap_acquire.c:162:15: warning: initialization makes pointer from
integer without a cast [-Wint-conversion]
oscap_acquire.c: In function 'write_to_memory_callback':
oscap_acquire.c:169:2: warning: implicit declaration of function
'oscap_buffer_append_binary_data' [-Wimplicit-function-declaration]
  oscap_buffer_append_binary_data((struct oscap_buffer*)userdata, ptr,
new_received_size);