Fix warning
src/common/util.h:366:9: error: ignoring return value of
'posix_memalign’ declared with attribute ‘warn_unused_result’
[-Werror=unused-result]